apiVersion: v1
kind: Service
metadata:
  name: chat-server
  namespace: chat-app
spec:
  type: ClusterIP
  selector:
    app: chat-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080