apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
      - name: chat-server
        image: chat-app/chat-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080