apiVersion: v1
kind: Service
metadata:
  name: chat-users
  namespace: chat-app
spec:
  type: ExternalName
  externalName: chat.users.com
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080